esphome:
  name: testinnovnow
  friendly_name: TestInnovNow

esp8266:
  board: esp01_1m

# Enable logging
logger:

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: i2c_max17043

# Enable Home Assistant API
api:
  encryption:
    key: "1M0t7/CVUy3JMomd5FaxJdWbLUIIKBEOweZX19SrjoU="

ota:
  - platform: esphome
    password: "644d1a3c6467e5dce8dfb58c1061465d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testinnovnow Fallback Hotspot"
    password: "OchHKU3SalIe"

captive_portal:

sensor:
  - platform: max17043
    id: max17043_id
    i2c_id: i2c_max17043
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    name: "Door Sensor"
    device_class: door
